AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-python-crud-sample

  SAM Template for sam-python-sample

Globals:
  Function:
    Timeout: 60

Parameters:
  Table:
    Type: String
    Default: Activities
  Region:
    Type: String
    Default: us-east-1
  AWSEnv:
    Type: String
    Default: AWS

Resources:
  GetActivityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get_activity/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          TABLE: !Ref Table
          REGION: !Ref Region
          AWSENV: !Ref AWSEnv
      Events:
        CreateActivities:
          Type: Api
          Properties:
            Path: /activities/{id}
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable
  
ActivitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
        -
          AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "date"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "Activities"

Outputs:
  ActivitiesApi:
    Description: "API Gateway endpoint URL for Prod stage for Create Activity Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/activities/"  CreateActivityFunction:
    Description: "Create Activity Lambda Function ARN"
    Value: !GetAtt CreateActivityFunction.Arn
  GetActivityFunction:
    Description: "Get Activity Lambda Function ARN"
    Value: !GetAtt GetActivityFunction.Arn
  GetActivityFunctionIamRole:
    Description: "Implicit IAM Role created for Get Activity function"
    value: !GetAtt GetActivityFunctionRole.Arn
